const OWNER='huocai250',REPO='huocai_web',FILE='posts.json',apiUrl=`https://api.github.com/repos/${OWNER}/${REPO}/contents/${FILE}`;
const escapeHtml=value=>(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const safeUrl=value=>/^https?:\/\//i.test(value)?value:'';
function markdown(text){let html=escapeHtml(text);html=html.replace(/```([\s\S]*?)```/g,'<pre><code>$1</code></pre>');html=html.replace(/@\[youtube\]\((https?:\/\/[^)]+)\)/g,(_,url)=>{const id=url.match(/(?:v=|youtu\.be\/)([\w-]+)/)?.[1];return id?`<div class="embed"><iframe src="https://www.youtube-nocookie.com/embed/${id}" title="YouTube video" allowfullscreen></iframe></div>`:'';});html=html.replace(/@\[video\]\((https?:\/\/[^)]+)\)/g,(_,url)=>`<video controls src="${safeUrl(url)}"></video>`);html=html.replace(/!\[([^\]]*)\]\((https?:\/\/[^)]+)\)/g,(_,alt,url)=>`<img src="${safeUrl(url)}" alt="${alt}" loading="lazy">`);html=html.replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,(_,label,url)=>`<a href="${safeUrl(url)}" target="_blank" rel="noreferrer">${label}</a>`);html=html.replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*([^*\n]+)\*/g,'<em>$1</em>').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h2>$1</h2>');return `<p>${html.replace(/\n\n/g,'</p><p>').replace(/\n/g,'<br>')}</p>`;}
const decode=value=>decodeURIComponent(escape(atob(value.replace(/\n/g,'')))),encode=value=>btoa(unescape(encodeURIComponent(value))),slug=new URLSearchParams(location.search).get('slug');
function loadGiscus(){const config=window.BLOG_CONFIG?.giscus;if(!config?.repoId||!config?.categoryId){document.querySelector('#giscus').innerHTML='<p>评论区正在配置中。</p>';return;}const script=document.createElement('script');script.src='https://giscus.app/client.js';script.async=true;script.crossOrigin='anonymous';script.setAttribute('data-repo',config.repo);script.setAttribute('data-repo-id',config.repoId);script.setAttribute('data-category',config.category);script.setAttribute('data-category-id',config.categoryId);script.setAttribute('data-mapping','specific');script.setAttribute('data-term',slug);script.setAttribute('data-reactions-enabled','1');script.setAttribute('data-theme','dark');document.querySelector('#giscus').replaceChildren(script);}
fetch(FILE).then(r=>r.json()).then(posts=>{const post=posts.find(item=>item.slug===slug);if(!post)throw new Error('文章不存在');document.title=`${post.title} / 火柴 TECH LOG`;document.querySelector('#meta').textContent=`${post.date} · ${post.tag||'TECH'}`;document.querySelector('#title').textContent=post.title;document.querySelector('#body').innerHTML=markdown(post.content);loadGiscus();}).catch(()=>{document.querySelector('#title').textContent='找不到这篇文章';document.querySelector('#body').innerHTML='<p>它可能尚未发布，或链接已失效。</p>';});
document.querySelector('#share').addEventListener('click',async()=>{const data={title:document.querySelector('#title').textContent,text:document.querySelector('#meta').textContent,url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);document.querySelector('#share').textContent='✓ 链接已复制';}}catch{}});
document.querySelector('#delete').addEventListener('click',()=>{document.querySelector('#delete-panel').hidden=false;document.querySelector('#delete-token').focus();});
document.querySelector('#confirm-delete').addEventListener('click',async()=>{if(!confirm('确定永久删除这篇文章吗？'))return;const token=document.querySelector('#delete-token').value.trim(),status=document.querySelector('#delete-status');status.textContent='正在删除…';try{const headers={Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json'},current=await fetch(apiUrl,{headers});if(!current.ok)throw new Error('无法读取文章索引，请检查令牌权限。');const data=await current.json(),posts=JSON.parse(decode(data.content)).filter(post=>post.slug!==slug);const result=await fetch(apiUrl,{method:'PUT',headers,body:JSON.stringify({message:`Delete: ${slug}`,content:encode(JSON.stringify(posts,null,2)),sha:data.sha})});if(!result.ok)throw new Error('删除失败，请检查令牌。');location.href='./';}catch(error){status.textContent=error.message;}});

